// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

export const FETCH_USERS_CREATED = 'FETCH_USERS_CREATED'
export const FETCH_USERS_CREATED_SUCCESS = 'FETCH_USERS_CREATED_SUCCESS'
export const FETCH_USERS_CREATED_FAILURE = 'FETCH_USERS_CREATED_FAILURE'

export const FETCH_GROUPS_MODERATING = 'FETCH_GROUPS_MODERATING'
export const FETCH_GROUPS_MODERATING_SUCCESS = 'FETCH_GROUPS_MODERATING_SUCCESS'
export const FETCH_GROUPS_MODERATING_FAILURE = 'FETCH_GROUPS_MODERATING_FAILURE'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'
